-- Video clips attached to a repair order/service line, same role as estimate_photos but the bytes
-- live in Cloudflare R2 (zero-egress storage) instead of Supabase Storage — video gets viewed
-- repeatedly by both shop staff and customers, and Supabase bills egress per view, which would get
-- expensive fast at any real scale. storage_key is the R2 object key; actual upload/playback goes
-- through presigned URLs generated by Netlify functions (create-video-upload-url.ts /
-- get-video-url.ts), never through this database directly.
--
-- RLS policies are a straight mirror of estimate_photos' — same owner/advisor/technician access
-- model, just renamed. Kept as a near-duplicate on purpose: one more case where, if the access
-- model for photos ever changes, this needs the same change applied by hand (there's no shared
-- policy function to update once for both tables).
create table public.estimate_videos (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null default auth.uid() references auth.users(id),
  repair_order_id uuid not null references public.repair_orders(id),
  service_group_id uuid not null,
  storage_key text not null unique,
  content_type text,
  duration_seconds numeric,
  caption text,
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

alter table public.estimate_videos enable row level security;

create policy "Owners can view estimate videos" on public.estimate_videos
  for select using (auth.uid() = owner_id);

create policy "Owners can add estimate videos" on public.estimate_videos
  for insert with check (auth.uid() = owner_id and owner_can_write(owner_id));

create policy "Owners can update estimate videos" on public.estimate_videos
  for update using (auth.uid() = owner_id) with check (auth.uid() = owner_id and owner_can_write(owner_id));

create policy "Owners can delete estimate videos" on public.estimate_videos
  for delete using (auth.uid() = owner_id and owner_can_write(owner_id));

create policy "Staff can view scoped estimate videos" on public.estimate_videos
  for select using (
    staff_can_view_all(owner_id)
    or (active_staff_role(owner_id) = 'service_advisor' and exists (
      select 1 from repair_orders ro
      where ro.id = estimate_videos.repair_order_id and ro.service_advisor_id = active_staff_id(ro.owner_id)
    ))
    or (active_staff_role(owner_id) = 'technician' and exists (
      select 1 from repair_order_technicians rot
      where rot.repair_order_id = estimate_videos.repair_order_id and rot.staff_id = active_staff_id(rot.owner_id)
    ))
  );

create policy "Advisors manage estimate videos" on public.estimate_videos
  for insert with check (active_staff_role(owner_id) = 'service_advisor' and owner_can_write(owner_id));

create policy "Advisors update estimate videos" on public.estimate_videos
  for update using (active_staff_role(owner_id) = 'service_advisor')
  with check (active_staff_role(owner_id) = 'service_advisor' and owner_can_write(owner_id));

create policy "Advisors delete estimate videos" on public.estimate_videos
  for delete using (active_staff_role(owner_id) = 'service_advisor' and owner_can_write(owner_id));

create policy "Technicians add videos on assigned ROs" on public.estimate_videos
  for insert with check (
    active_staff_role(owner_id) = 'technician' and owner_can_write(owner_id) and exists (
      select 1 from repair_order_technicians rot
      where rot.repair_order_id = estimate_videos.repair_order_id and rot.staff_id = active_staff_id(rot.owner_id)
    )
  );
